#!/usr/bin/env bash
# Render a Kubernetes manifest for one Apiary site: a StatefulSet of N Nodes whose
# keys live in a Secret (so a rescheduled pod is the same Node), a headless
# Service that lists the pods, a ConfigMap and the join token.
#
#   deploy/k8s/render.sh --apiary factory --colony line1 --replicas 3 \
#       --apiary-key ./apiary.key --image ghcr.io/you/apiary:latest > site.yaml
#   kubectl apply -f site.yaml
#
# Needs the `apiary` binary on the PATH (it makes the keys and the token). The
# Apiary key stays with you: it signs the token here and goes nowhere near the
# cluster.
set -euo pipefail

apiary_name="" colony="" replicas=3 key="" image="" namespace="default" relay=""
while [ $# -gt 0 ]; do
  case "$1" in
    --apiary) apiary_name="$2"; shift 2 ;;
    --colony) colony="$2"; shift 2 ;;
    --replicas) replicas="$2"; shift 2 ;;
    --apiary-key) key="$2"; shift 2 ;;
    --image) image="$2"; shift 2 ;;
    --namespace) namespace="$2"; shift 2 ;;
    --relay) relay="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
for v in apiary_name colony key image; do
  [ -n "${!v}" ] || { echo "missing --${v//_/-}" >&2; exit 2; }
done

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
public=$(apiary key public --key "$key")

# Each pod's key is a 32-byte secret like the Apiary's; its public half is the
# pod's Node id.
ids=()
for i in $(seq 0 $((replicas - 1))); do
  apiary key generate --out "$work/apiary-$i.key" > /dev/null
  ids+=("$(apiary key public --key "$work/apiary-$i.key")")
done

bootstrap=()
for id in "${ids[@]}"; do bootstrap+=(--bootstrap "$id@"); done
relay_args=()
[ -n "$relay" ] && relay_args=(--relay "$relay")
token=$(apiary token issue --key "$key" --apiary "$apiary_name" --colony "$colony" \
  --caps run,ingest --days 365 "${bootstrap[@]}" "${relay_args[@]}")

dns_peers=""
for i in $(seq 0 $((replicas - 1))); do
  dns_peers+="    [[net.dns_peers]]"$'\n'
  dns_peers+="    id = \"${ids[$i]}\""$'\n'
  dns_peers+="    host = \"apiary-$i.apiary.$namespace.svc\""$'\n'
  dns_peers+="    port = 7000"$'\n'
done
relays_line=""
[ -n "$relay" ] && relays_line="    relays = [\"$relay\"]"

cat <<YAML
# Generated by deploy/k8s/render.sh. Do not commit: it holds Node keys and a token.
apiVersion: v1
kind: Secret
metadata:
  name: apiary-keys
  namespace: $namespace
type: Opaque
stringData:
YAML
for i in $(seq 0 $((replicas - 1))); do
  printf '  apiary-%s.key: "%s"\n' "$i" "$(tr -d '\n' < "$work/apiary-$i.key")"
done
cat <<YAML
---
apiVersion: v1
kind: Secret
metadata:
  name: apiary-token
  namespace: $namespace
type: Opaque
stringData:
  token: "$token"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apiary-config
  namespace: $namespace
data:
  apiary.toml.template: |
    [node]
    storage = "@STORAGE@"
    cache_dir = "/cache"

    [flight]
    listen = "0.0.0.0:50051"

    [net]
    apiary = "$apiary_name"
    apiary_public_key = "$public"
    token_file = "/etc/apiary/token/token"
    key_file = "/etc/apiary/keys/@POD@.key"
    site = "@POD_SITE@"
    udp_port = 7000
    mdns = false
    serve_comb = @SERVE_COMB@
$relays_line
$dns_peers
---
# A headless Service: its DNS name resolves to every pod's address, which is how
# the Nodes find each other without any registry.
apiVersion: v1
kind: Service
metadata:
  name: apiary
  namespace: $namespace
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: apiary
  ports:
    - { name: quic, port: 7000, protocol: UDP }
    - { name: flight, port: 50051, protocol: TCP }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apiary
  namespace: $namespace
spec:
  serviceName: apiary
  replicas: $replicas
  podManagementPolicy: Parallel
  selector:
    matchLabels: { app: apiary }
  template:
    metadata:
      labels: { app: apiary }
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: apiary
          image: $image
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              pod=\$(hostname)
              # Pod 0 has the drive (the PersistentVolume) and serves it; the
              # others reach it through pod 0's Node id.
              if [ "\$pod" = "apiary-0" ]; then
                storage="local:///comb"; serve=true
              else
                storage="apiary-drive://${ids[0]}/"; serve=false
              fi
              sed -e "s|@STORAGE@|\$storage|" -e "s|@POD@|\$pod|" \
                  -e "s|@POD_SITE@|$namespace|" -e "s|@SERVE_COMB@|\$serve|" \
                  /etc/apiary/config/apiary.toml.template > /run/apiary.toml
              exec apiary node run --config /run/apiary.toml
          ports:
            - { name: quic, containerPort: 7000, protocol: UDP }
            - { name: flight, containerPort: 50051, protocol: TCP }
          volumeMounts:
            - { name: config, mountPath: /etc/apiary/config }
            - { name: keys, mountPath: /etc/apiary/keys, readOnly: true }
            - { name: token, mountPath: /etc/apiary/token, readOnly: true }
            - { name: cache, mountPath: /cache }
            - { name: comb, mountPath: /comb }
          readinessProbe:
            tcpSocket: { port: 50051 }
            periodSeconds: 5
      volumes:
        - { name: config, configMap: { name: apiary-config } }
        - { name: keys, secret: { secretName: apiary-keys, defaultMode: 0400 } }
        - { name: token, secret: { secretName: apiary-token, defaultMode: 0400 } }
        # The crop, the cache and spill: node-local, rebuilt if the pod moves
        # (what the crop held and had not deposited goes with it: see the loss window).
        - { name: cache, emptyDir: {} }
  volumeClaimTemplates:
    # The comb. Only apiary-0 uses its claim; it is the drive.
    - metadata: { name: comb }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: 10Gi } }
YAML
